#!/usr/bin/env python3
"""Turn the authored lesson text into the course data the game ships with."""
import json, re, sys, importlib.util, pathlib

def parse_words(text):
    out=[]
    for line in text.strip().split('\n'):
        line=line.strip()
        if not line: continue
        parts=[x.strip() for x in line.split('|')]
        out.append({'en':parts[0],'ic':parts[1] if len(parts)>1 else '','def':parts[2] if len(parts)>2 else ''})
    return out

def parse_grammar(text):
    out=[]
    for raw in text.strip().split('\n'):
        line=raw.strip()
        if not line: continue
        k='ch'
        if line[0]=='?': k,line='in',line[1:].strip()
        elif line[0]=='#': k,line='sq',line[1:].strip()
        elif line[0]=='!': k,line='er',line[1:].strip()
        p=[x.strip() for x in line.split('|')]
        if k=='in':
            assert len(p)>=2, 'in needs an answer: '+raw
            out.append({'k':k,'q':p[0],'a':'|'.join(x.strip() for x in p[1].split(';') if x.strip()),'ee':p[2] if len(p)>2 else ''})
        elif k=='sq':
            out.append({'k':k,'q':'Put the words in the correct order','a':p[0],'ee':p[1] if len(p)>1 else ''})
        else:
            assert len(p)>=3, 'needs options and an index: '+raw
            o=[x.strip() for x in p[1].split(';') if x.strip()]
            a=int(p[2])-1
            assert 0<=a<len(o), 'bad answer index: '+raw
            out.append({'k':k,'q':p[0],'o':o,'a':a,'ee':p[3] if len(p)>3 else ''})
    return out

def L(name, words='', grammar=''):
    return {'name':name,'words':parse_words(words) if words else [],
            'grammar':parse_grammar(grammar) if grammar else []}

def validate(course):
    errs=[]; stats={'lessons':0,'words':0,'grammar':0,'kinds':{}}
    seen_words=set()
    for se in course['sections']:
        for le in se['lessons']:
            stats['lessons']+=1
            tag=se['name']+' / '+le['name']
            ws=le['words']
            stats['words']+=len(ws)
            if len(ws)<6: errs.append(f'{tag}: only {len(ws)} words')
            en=set()
            for w in ws:
                if w['en'] in en: errs.append(f'{tag}: duplicate word "{w["en"]}"')
                en.add(w['en'])
                if not w['def']: errs.append(f'{tag}: "{w["en"]}" has no definition')
                elif len(w['def'])<12: errs.append(f'{tag}: definition too short for "{w["en"]}"')
                if w['def'] and re.search(r'\b'+re.escape(w['en'].split()[0])+r'\b', w['def'], re.I):
                    errs.append(f'{tag}: definition gives away "{w["en"]}"')
            gs=le['grammar']
            stats['grammar']+=len(gs)
            if len(gs)<20: errs.append(f'{tag}: only {len(gs)} grammar questions')
            qs=set()
            for q in gs:
                stats['kinds'][q['k']]=stats['kinds'].get(q['k'],0)+1
                key=q.get('q','')+str(q.get('a'))
                if key in qs: errs.append(f'{tag}: duplicate question "{q.get("q","")[:40]}"')
                qs.add(key)
                if not q.get('ee'): errs.append(f'{tag}: no explanation for "{q.get("q","")[:40]}"')
                if q['k'] in ('ch','er'):
                    o=q['o']
                    if len(o)<3 and q['k']=='ch': errs.append(f'{tag}: only {len(o)} options for "{q["q"][:40]}"')
                    if len(set(o))!=len(o): errs.append(f'{tag}: repeated options in "{q["q"][:40]}"')
                if q['k']=='ch' and '___' not in q['q'] and not re.search(r'\?|Choose|Which|What|correct', q['q']):
                    errs.append(f'{tag}: choice question has no gap and no question form: "{q["q"][:50]}"')
                if q['k']=='in' and not q['a']: errs.append(f'{tag}: empty typed answer')
                if q['k']=='sq' and len(q['a'].split())<4: errs.append(f'{tag}: word-order sentence too short')
            kinds=set(x['k'] for x in gs)
            if len(kinds)<3: errs.append(f'{tag}: only kinds {sorted(kinds)} — needs more variety')
    return errs, stats

def build(modules, out_js):
    sections=[]
    for m in sorted(modules):
        spec=importlib.util.spec_from_file_location(pathlib.Path(m).stem, m)
        mod=importlib.util.module_from_spec(spec)
        mod.L=L
        spec.loader.exec_module(mod)
        sections.append(mod.SECTION)
    courses=[{'name':'English 10–12 · Intermediate','sections':sections}]
    allerr=[]; tot={'lessons':0,'words':0,'grammar':0,'kinds':{}}
    for c in courses:
        e,st=validate(c); allerr+=e
        for k in ('lessons','words','grammar'): tot[k]+=st[k]
        for k,v in st['kinds'].items(): tot['kinds'][k]=tot['kinds'].get(k,0)+v
    print(json.dumps(tot))
    if allerr:
        print('PROBLEMS:', len(allerr))
        for e in allerr[:40]: print('  -',e)
        return False
    banner=("/* Course that ships with the game.\n"
            "   Generated by tools/build_course.py from authoring/course/*.py — do not edit by hand. */\n")
    js=banner+'const BUILTIN_COURSES='+json.dumps(courses,ensure_ascii=False,separators=(',',':'))+';\n'
    open(out_js,'w').write(js)
    print('wrote', out_js, len(js)//1024, 'KB')
    return True

if __name__=='__main__':
    import glob
    root=pathlib.Path(__file__).resolve().parent.parent
    mods=sorted(glob.glob(str(root/'authoring'/'course'/'*.py')))
    out=root/'data'/'courses'/'english-10-12-intermediate.js'
    sys.exit(0 if build(mods, out) else 1)
